name: Notify Discord on version change

on:
  push:
    paths:
      - ".verson.json"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Discord message
        id: build
        run: |
          VERSION="$(jq -r '.version' .verson.json)"
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
          BRANCH="${GITHUB_REF_NAME}"
          README_LINK="${REPO_URL}/blob/${BRANCH}/README.md"
          CHANGELOG="$(head -c 1800 README.md || true)"
          printf 'Hey a new version of the VVunderlore Toolkit is available. Its version **%s**.\n\nHere is the changelog:\n%s\n\nFull changelog: %s\n' \
            "$VERSION" "$CHANGELOG" "$README_LINK" > message.txt
          jq -n --rawfile content message.txt '{content: $content}' > payload.json

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_KEY }}
        run: |
          curl -sS -X POST -H "Content-Type: application/json" \
            -d @payload.json "$DISCORD_WEBHOOK"
